import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import ActionSectionContextProvider from "@/context/Action-Section-Context";
import ThemeContextProvider from "@/context/Theme-Context";
import { Toaster } from "react-hot-toast";
import ThemeSwitch from "@/components/Theme-Switch";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
          <body
            className={`${inter.className} bg-gray-50 text-gray-950 relative pt-28 sm:pt-36 dark:bg-gray-900 dark:text-gray-50 dark:text-opacity-90`}
          >
            <div className="bg-[#b2bffe] absolute top-[-6rem] -z-10 right-[11rem] h-[31.25rem] w-[31.25rem] rounded-full blur-[10rem] sm:w-[68.75rem] dark:bg-[#946263]"></div>
            <ThemeContextProvider>
              <ActionSectionContextProvider>
                  <Header/>
                  {children}
                  <Footer/>
                  <Toaster position="top-right"/>
                  <ThemeSwitch/>
              </ActionSectionContextProvider>
            </ThemeContextProvider>
          </body>
    </html>
  );
}